### ISSUE TITLE
Fail to find layouts/index.tsx when sourceRoot is /

### ISSUE THREAD

**Issue by xile611** [prijs/pri#13]
![image](https://user-images.githubusercontent.com/6111424/45534054-5fcad400-b82c-11e8-9a9d-7af34fa7b858.png)

![image](https://user-images.githubusercontent.com/6111424/45534062-65281e80-b82c-11e8-9423-921253a78602.png)

![image](https://user-images.githubusercontent.com/6111424/45534072-6c4f2c80-b82c-11e8-8170-08b04e990160.png)

**Comment by ascoders** [comment]
Source root should be a relative path `./`.
