### ISSUE TITLE
有几点疑惑？

### ISSUE THREAD

**Issue by zhaomin94** [prijs/pri#16]
您好！对您的pri很感兴趣，我就大致看了一下源码，发现有几点疑惑：
1、Windows不支持，Pri大致有哪些地方不支持Windows？
2、并未发现定义`pri init`命令，那如何使用了该命令？
3、发现源码里有互相调用的情况，比如plugins.ts 和 很多文件，这样写法是不是有点不合理？
谢谢您！

**Comment by ascoders** [comment]
1. windows 不支持一些命令比如 `cwd`。
2. `npx pri init`。
3. Pri 是高度插件化的，所以相互调用会很多。

**Comment by zhaomin94** [comment]
谢谢！
不支持windows着实有点难受，`npx pri init`默认执行`./bin/pri`?

**Comment by ascoders** [comment]
是的。

**Comment by ascoders** [comment]
windows 可以用比如 fedora，支持类 linux 命令行。
