### ISSUE TITLE
关于生成的配置文件的问题

### ISSUE THREAD

**Issue by kinghoo5201** [prijs/pri#21]
如果本地已经生成了配置文件如：
tsconfig.json
tscofnig.jest.json
tslint.json
.vscode/settings.json

如果已经存在，能否不在运行或者打包的过程中进行覆盖：用户修改了配置得以保存
@ascoders

**Comment by ascoders** [comment]
.vscode/settings.json 是半覆盖，只会保证几个 key 存在。
其它都是强制覆盖。看下有什么具体的需求？

**Comment by kinghoo5201** [comment]
就是这些配置在pri init的时候是自动创建的，但是后续当存在的时候不去覆盖，或许可以弄个是否强刷的开关在priconfig.json里

**Comment by ascoders** [comment]
@kinghoo5201 强制就为了保持项目环境一致，能否把具体要修改的项列出来，我们一起评估一下？

**Comment by kinghoo5201** [comment]
> @kinghoo5201 强制就为了保持项目环境一致，能否把具体要修改的项列出来，我们一起评估一下？

由于项目开发是需要保持环境一致，但是开源部分用户可能不需要这些强制的东西，或者项目有特殊需求的时候也不需要这些强制的东西，可能都需要制作plugin来进行修改，
我觉得可以在配置中加入

1. 启动项目/build不覆盖tsconfig的开关
2.启动项目/build不覆盖tslint的开关
3.pri init的时候是否暴露入口文件给用户的选项
4.pri init的时候执行的脚本不支持windows系统
对于需要覆盖可以以这种形式你看是否可行@ascoders
在priconfig.json中加入文件覆盖选项
{
"file":{
"tsconfig.json":{
...filecontent
}
}
}
这种形式来进行根据文件名来自定义覆盖内容

**Comment by ascoders** [comment]
@kinghoo5201 可以写个 pri 插件，读取 priconfig.json 或者 package.json 的内容，作为刷新 tslint、tsconfig 等文件的输入，这样就放开了。

但 pri 不会内置这个功能，默认还是要收紧配置。

**Comment by kinghoo5201** [comment]
ok,got it
