### ISSUE TITLE
在prijs项目中引入css，css中引入字体会报错

### ISSUE THREAD

**Issue by kinghoo5201** [prijs/pri#23]
在项目中css @font-face引入本地ttf/eot/woff/svg等字体会引发报错，是需要有啥配置来实现还是，prijs没有像cra脚手架那样集成了这些文件的loader。需要怎样配置才能解决这个问题呢

![image](https://user-images.githubusercontent.com/25658415/53434977-adca4180-3a32-11e9-849f-421fdcaeeed2.png)
![image](https://user-images.githubusercontent.com/25658415/53434978-adca4180-3a32-11e9-9901-95ac1cc8b1d0.png)
这是复现操作
@ascoders

**Comment by ascoders** [comment]
以内置对字体文件的处理
