### ISSUE TITLE
Unexpected file or directory

### ISSUE THREAD

**Issue by zhanba** [prijs/pri#4]
win7, run `npx pri init` and get this

Error: Unexpected file or directory: ...\pri-demo\src\pages\index.tsx
 at ...\pri-demo\node_modules\pri\built\node\project\check-project-files.js:55:31

**Comment by ascoders** [comment]
@zhanba  Sorry i don't have Windows computer, can you check the method here first? https://github.com/prijs/pri/blob/master/src/built-in-plugins/project-analyse-pages/index.ts#L28

And may sure upgrade to `0.7.10`.

**Comment by zhanba** [comment]
seem like path seperator problem in 'src\page'

**Comment by ascoders** [comment]
Map be use `path.sep` instead of `/` will work.

**Comment by ascoders** [comment]
Try `0.7.12`, but i'm not sure fixed all problem in windows.

**Comment by zhanba** [comment]
Error: Unexpected file or directory: ...\pri-demooooo\node_modules\.bin

**Comment by ascoders** [comment]
I borrowed a windows computer, and will test it tomorrow.

**Comment by ascoders** [comment]
Fedora is awesome! Can this issue be closed?

**Comment by ascoders** [comment]
Because of no other questions, I closed this issue.
