### ISSUE TITLE
启动端口是多少？

### ISSUE THREAD

**Issue by wysj** [prijs/pri#40]
启动端口是多少？

**Comment by ascoders** [comment]
项目类型 `npm start` 会自动找端口号，也可以通过 [devPort](https://prijs.github.io/pri-docs/usage/config/#devPort%20%3Ccode%3Enumber%3C%2Fcode%3E%20%3Ccode%3E%5BAuto%20get%20free%20port%5D%3C%2Fcode%3E) 指定，更多详情可以看文档。
