### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by CharlieLau** [prijs/pri#6]
大佬有没有考虑 
 1.抽离一个pri-core ，类似babel的插件使用方式
2. 项目template可不可以扩展呢，比如我想扩展vue栈

**Comment by ascoders** [comment]
看似内置了很多插件，但全部都是必要且核心的，插件拓展方式是有的：https://prijs.github.io/pri-docs/plugin-setup/

第二个其实不建议基于 pri 拓展，因为 pri 本身依赖了 react，webui 的基础代码也是用 react 写的。我觉得更适合写一个 vue 版的，把 react 依赖拿掉。

**Comment by CharlieLau** [comment]
好滴，如果不介意，我fork一份，重写vue栈，O(∩_∩)O哈哈~

**Comment by ascoders** [comment]
可以的
