### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ChiaJune** [prijs/pri#8]
您好！对您的`pri`比较感兴趣。我想问一下，如何用`pri`实现像[ant-design-pro](https://pro.ant.design/docs/authority-management-cn)那样的权限管理？
后期会出一些项目案例么？

**Comment by ascoders** [comment]
后期会增加权限路由功能，通过自定义路由实现：

**Comment by ChiaJune** [comment]
谢谢您的回复:pray:！
基于角色的访问控制是否好做呢？现在的路由是封装过的，感觉限制比较多（老实说，目前还未使用`pri`写过项目，可能感觉是错误的:laughing:）。这周末来试一试~

**Comment by ascoders** [comment]
基于角色的访问控制是业务逻辑，由权限组件来判断。

**Comment by ChiaJune** [comment]
👌
