### ISSUE TITLE
Recovered tsconfig cause throwing path.replace is not a function error.

### ISSUE THREAD

**Issue by DannySu09** [prijs/pri#9]
I try to run `npm run docs` in your another project [gaea-editor](https://github.com/ascoders/gaea-editor)，and the `tsconfig.json` file is recovered as below:

```json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "strictNullChecks": false,
    "jsx": "react",
    "target": "esnext",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "./",
    "baseUrl": ".",
    "lib": [
      "dom",
      "es5",
      "es6",
      "scripthost"
    ],
    "paths": {
      "pri/*": [
        "pri",
        ".temp/types/*"
      ]
    }
  },
  "include": [
    ".temp/**/*",
    [
      "src/**/*",
      "tests/**/*",
      "docs/**/*"
    ]
  ],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

The value of `include` property has an array in the outer array, that looks weird. 

It's generated by the function `ensureTsconfig` in `src/built-in-plugins/ensure-project-files/index.ts`.

TypeScript treat the array as a string, try to invoke `replace` function, this might explained why the error is thrown.

**Comment by ascoders** [comment]
@sunaiwen Thank you for your reminding. It's a bug, and has been fixed in version `0.11.25`.
